package ec.com.vipsoft.ce.clientapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-01-08T16:22:29.060-05:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://service.backend.ce.vipsoft.com.ec/", name = "AdministradorEntidad")
@XmlSeeAlso({ObjectFactory.class})
public interface AdministradorEntidad {

    @RequestWrapper(localName = "crearEntidad", targetNamespace = "http://service.backend.ce.vipsoft.com.ec/", className = "ec.com.vipsoft.ce.clientapi.CrearEntidad")
    @WebMethod
    @ResponseWrapper(localName = "crearEntidadResponse", targetNamespace = "http://service.backend.ce.vipsoft.com.ec/", className = "ec.com.vipsoft.ce.clientapi.CrearEntidadResponse")
    public void crearEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3
    );
}
